import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Footer from "@/components/main-footer";
import cn from "@/utils/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-[#060522]")}>
        <div className="min-h-screen h-auto overflow-x-hidden bg-[#060522] font-mono">
          <main className="min-h-screen h-auto">{children}</main>
          <div className="py-10">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
